import { computed } from "vue";
import {
  canUseSocial,
  closeProfilePanel,
  fetchSocialOverview,
  onlineFriends,
  openConversation,
  openFriendProfile,
  openProfilePanel,
  removeFriend,
  respondFriendRequest,
  respondRoomInvite,
  searchSocialUsers,
  sendFriendRequest,
  sendSocialMessage,
  socialActiveTab,
  socialChatDraft,
  socialChatFriendId,
  socialChatMessages,
  socialFriends,
  socialInvitePrompt,
  socialNotificationCount,
  socialProfile,
  socialProfileLoading,
  socialProfileVisible,
  socialSearchKeyword,
  socialSearchResults,
  socialSearchEmptyMessage,
  toggleWaitingFriendDrawer,
  inviteFriendToRoom,
  socialDrawerOpen,
  socialFriendNotificationCount,
  socialOverview,
} from "@/store/socialStore.js";

const pendingRequests = computed(
  () => socialOverview.value.pendingFriendRequests || [],
);

export {
  canUseSocial,
  closeProfilePanel,
  fetchSocialOverview,
  socialFriends as friends,
  onlineFriends,
  openConversation,
  openFriendProfile,
  openProfilePanel,
  removeFriend,
  pendingRequests,
  respondFriendRequest,
  respondRoomInvite,
  searchSocialUsers,
  sendFriendRequest,
  sendSocialMessage,
  socialActiveTab,
  socialChatDraft,
  socialChatFriendId,
  socialChatMessages,
  socialDrawerOpen,
  socialFriendNotificationCount,
  socialInvitePrompt,
  socialNotificationCount,
  socialOverview,
  socialProfile,
  socialProfileLoading,
  socialProfileVisible,
  socialSearchKeyword,
  socialSearchResults,
  socialSearchEmptyMessage,
  toggleWaitingFriendDrawer,
  inviteFriendToRoom,
};
