app.auth.redis-enabled=true

spring.datasource.url=${POKER_DB_URL:jdbc:mysql://127.0.0.1:3307/poker_auth?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${POKER_DB_USERNAME:poker}
spring.datasource.password=${POKER_DB_PASSWORD:poker123}
spring.datasource.driver-class-name=${POKER_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/common,classpath:db/migration/mysql

spring.session.store-type=redis
spring.data.redis.host=${POKER_REDIS_HOST:127.0.0.1}
spring.data.redis.port=${POKER_REDIS_PORT:6380}
